### ISSUE TITLE
Response to validate_file_get is Encoding:ASCII-8BIT, but contains UTF-8 characters

### ISSUE THREAD

**Issue by dgmstuart** [zerobounce/zero-bounce-ruby#8]
It looks like the batch file response isn't correctly encoded:

```ruby
response = Zerobounce.validate_file_get(file_id)
# > "\xEF\xBB\xBF\"an.email.address@example.com\"....
response.encoding 
> #<Encoding:ASCII-8BIT>
```

Those leading characters are UTF-8, but aren't interpreted correctly due to the encoding of the string. 

But either way, to get it to parse correctly as a CSV I first need to remove these Byte Order Mark (BOM) characters:

```ruby
response.force_encoding("UTF-8").sub(/^\xEF\xBB\xBF/, '')
```

**Comment by dgmstuart** [comment]
More information:

If I encode the file I _send_ as UTF-8, this doesn't make any difference.

The issue with parsing is that the first token will look like this

```ruby
\xEF\xBB\xBF/\"Email\"... 
```
    
Which gives an error:

    CSV::MalformedCSVError: Illegal quoting in line 1
    
This is because Ruby's CSV library is trying to parse that whole string, including the BOM as a single token, which is invalid because the opening quote is in the middle of the string.

**Comment by dgmstuart** [comment]
Here's the solution I ended up with:

```ruby
raw_file = client.validate_file_get(file_id)
csv_data = StringIO.new(raw_file)
csv_data.set_encoding_by_bom # The response comes back as ASCII, but with a UTF-8 BOM, which this method consumes
csv = CSV.parse(csv_data, headers: true)
```

**Comment by andreit-sst** [comment]
Hello @dgmstuart and thank you for your submission.

The ZeroBounce API is, indeed, serving a CSV file via `client.validate_file_get(file_id)` which usually starts with the BOM sequence. I will integrate your fix in `validate_file_get()` so it would return CSV parsable contents.
