### ISSUE TITLE
Batch file response is different to what is documented

### ISSUE THREAD

**Issue by dgmstuart** [zerobounce/zero-bounce-ruby#9]
This is what is documented in the README:

```
=> "\"email\",\"first\",\"last\",\"gender\",\"ip\",\"ZB Status\",\"ZB Sub Status\",\"ZB Account\",\"ZB Domain\",\"ZB First Name\",\"ZB Last Name\",\"ZB Gender\",\"ZB Free Email\",\"ZB MX Found\",\"ZB MX Record\",\"ZB SMTP Provider\",\"ZB Did You Mean\"\n\"disposable@example.com\",\"First\",\"Last\",\"male\",\"127.0.0.1\",\"do_not_mail\",\"disposable\",\"\",\"\",\"zero\",\"bounce\",\"male\",\"False\",\"true\",\"mx.example.com\",\"example\",\"\"\n"
```

...but what I actually get is more like this:

```
"\xEF\xBB\xBF\"disposable@example.com\",\"\",\"\",\"\",\"ZB Status\",\"ZB Sub Status\",\"ZB Account\",\"ZB Domain\",\"ZB First Name\",\"ZB Last Name\",\"ZB Gender\",\"ZB Free Email\",\"ZB MX Found\",\"ZB MX Record\",\"ZB SMTP Provider\",\"ZB Did You Mean\"\n\"disposable@example.com\",\"\",\"\",\"\",\"valid\",\"\",\"disposable\",\"example.com\",\"\",\"\",\"\",\"True\",\"true\",\"mx.example.com\",\"example\",\"\"\n
```

The following things are unexpected:
1. UTF-8 characters at the start of the file
2. the last processed email address is the first thing in the file
3. none of the lowercase headers (email, first, last etc) - just empty strings

**Comment by dgmstuart** [comment]
Actually I can see that this is the same content as the `..._all_results.csv` file which I can see by downloading the results through the UI. 

But it's still confusing and doesn't match the documentation.

**Comment by dgmstuart** [comment]
OK, this seems to be because I'm sending a text file of email addresses:

```
disposable@example.com
email@example.com
```

...because the documentation says I can send a txt file: https://www.zerobounce.net/docs/email-validation-api-quickstart/#send_file__v2__

...but the system is interpreting this file as a CSV and assuming that the first row is a header row. 

I think this repo needs some clearer documentation, ideally with some examples. It's also pretty confusing that you say that it can be a txt file, but the contents is always expected to be CSV formatted.

**Comment by andreit-sst** [comment]
Hello @dgmstuart and thank you for your submission.

The first point on your list will be handled in a PR targeting your other issue. Hopefully I will answer your following points also.

Regarding the method `validate_file_send()` :
* the files submitted in both this method and `scoring_file_send()` are expected to have csv format (whether they're `.csv` or `.txt`) 
* the response file received via `validate_file_get()` will contain the data columns of the file submitted on `validate_file_send()` WITH headers and additional columns concatenated to the right of the submitted columns
* the expected additional columns are the following:
```
"ZB Status","ZB Sub Status","ZB Account","ZB Domain","ZB First Name","ZB Last Name","ZB Gender","ZB Free Email","ZB MX Found","ZB MX Record","ZB SMTP Provider","ZB Did You Mean","ZB City","ZB Region/State","ZB Zip Code","ZB Country"
```
* when `has_header_row: true`, the response file will include the columns that were provided in the submitted file
* when `has_header_row: false`:
    * columns that were specified via parameters (when calling `validate_file_send()`) will result in the following column titles:
      ```
      email_address_column    => "Email Address"
      first_name_column       => "First Name"
      last_name_column        => "Last Name"
      gender_column           => "Gender"
      ```
    * columns that are not specified explicitly will be provided column title "Custom"

Will update the README with the details I provided here as well as samples (request,response,params) in a future PR.

Hope this helps.
